// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Charge .env.local (convention Next.js) puis .env en fallback.
loadEnv({ path: ".env.local" });
loadEnv({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Commande exécutée par `npx prisma db seed` (et après `migrate reset`).
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Connexion directe (port 5432) : requise par Prisma Migrate.
    // Fallback sur DATABASE_URL si DIRECT_URL n'est pas défini (dev local).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
